<?php

namespace Fideism\DatabaseUuid\Tests;


class RunTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testEvents()
    {
        $this->assertTrue(true);
    }
}
